# Generated by Django 5.0.1 on 2024-02-05 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, default=datetime.date(2024, 2, 5))),
                ('content', models.TextField(max_length=1500)),
            ],
        ),
    ]
