# Generated by Django 5.0.1 on 2024-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0003_session_slug_alter_userdata_nim'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='available',
            field=models.IntegerField(default=7),
        ),
    ]
