# Generated by Django 5.0.1 on 2024-01-15 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0006_alter_userdata_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='war.schedule'),
        ),
    ]
