# Generated by Django 5.0.1 on 2024-01-15 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0007_alter_userdata_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 0)),
            preserve_default=False,
        ),
    ]
