# Generated by Django 5.0.1 on 2024-01-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0008_session_open_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='open_date',
            new_name='open_time',
        ),
    ]
