# Generated by Django 5.0.1 on 2024-02-05 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0011_event_presence_presenceuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresenceUser',
            new_name='PresenceData',
        ),
    ]
