# Generated by Django 5.0.1 on 2026-01-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0012_rename_presenceuser_presencedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='users_enrolled', to='war.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='max_enrolled',
            field=models.IntegerField(default=30),
        ),
    ]
