# Generated by Django 5.0.1 on 2026-01-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0013_userdata_schedules_alter_schedule_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='schedule',
        ),
    ]
